### ISSUE TITLE
new error message for terms with no data

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#10]
For a term that has no data (i.e., it's collector just started), the error should say "No data for [term] yet. Please check back." Right now, it gives a pop up error that's meaningless to end users and inaccurate for developers (there is a term id, there's just no data associated with it).

![screen shot 2017-04-07 at 9 09 37 pm](https://cloud.githubusercontent.com/assets/182478/24824722/9355722e-1bd6-11e7-94fa-b4950b182d19.png)

**Comment by libbyh** [comment]
Doesn't actually need to be a pop up dialog box at all. Can just be a message inside the view where data will eventually show up.

**Comment by pratik27shah** [comment]
Ok..wil resolve it right way

**Comment by pratik27shah** [comment]
issue fixed,check if this is fine.
![errorvalues](https://cloud.githubusercontent.com/assets/17016381/24825150/8fcc32c0-1bde-11e7-9888-4ed8d337a4de.PNG)

**Comment by libbyh** [comment]
Close, but "Value not found" still doesn't explain to the user or the dev what the problem is. It should say "No data for that term. Please check back." I see two lines in /app/templates/collector.html - [281](http://github.com/casmlab/stack/blob/e10c39a/app/templates/collector.html#L281) and [335](http://github.com/casmlab/stack/blob/e10c39a/app/templates/collector.html#L335) - that show this error. Do they show it for the same reasons? Why two places?

**Comment by pratik27shah** [comment]
done

**Comment by libbyh** [comment]
Should list the actual term instead of the word term - e.g., "No data for defenceupdate". 

The item clicked isn't viewable anymore, and we need to remind users what they selected.

**Comment by pratik27shah** [comment]
ok..

**Comment by libbyh** [comment]
I still see the generic "No data for the term" message.
![screen shot 2017-04-11 at 10 16 51 am](https://cloud.githubusercontent.com/assets/182478/24916574/2581f62e-1ea0-11e7-8de8-5113044675d1.png)

**Comment by pratik27shah** [comment]
its working fine
